version: '3.9'

services:
    node_exporter:
        image: prom/node-exporter:latest
        container_name: node_exporter
        restart: unless-stopped
        networks:
            - web
        ports:
            - "9100:9100"
        volumes:
            - /proc:/host/proc:ro
            - /sys:/host/sys:ro
            - /:/rootfs:ro
        command:
            - '--path.procfs=/host/proc'
            - '--path.sysfs=/host/sys'
            - '--path.rootfs=/rootfs'
            - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'


    postgresql:
        image: postgres:17.0
        restart: unless-stopped
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_MAX_CONNECTIONS: 200
        networks:
            - web
        ports:
            - '5432:5432'

    rabbitmq:
        image: rabbitmq:3-management
        restart: unless-stopped
        networks:
            - web
        ports:
            - "5672:5672"
            - "15672:15672"
        environment:
            RABBITMQ_DEFAULT_USER: rabbitmq
            RABBITMQ_DEFAULT_PASS: rabbitmq

    rabbitmq_exporter:
        image: kbudde/rabbitmq-exporter:latest
        container_name: rabbitmq_exporter
        restart: unless-stopped
        environment:
            RABBITMQ_URL: "http://rabbitmq:rabbitmq@rabbitmq:15672"
            RABBIT_USER: "rabbitmq"
            RABBIT_PASSWORD: "rabbitmq"
        networks:
            - web
        ports:
            - "9419:9419"
        depends_on:
            - rabbitmq

    traefik:
        image: traefik:latest
        restart: unless-stopped
        networks:
            - web
        ports:
            - '80:80'
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        labels:
            - 'traefik.enable=true'
            - 'traefik.docker.network=web'
            - 'traefik.http.routers.traefik.service=traefik'
            - 'traefik.http.routers.traefik.rule=Host(`traefik.localhost`)'
            - 'traefik.http.services.traefik.loadbalancer.server.port=8080'
        command: --api.insecure=true --providers.docker

    pgadmin:
        image: dpage/pgadmin4
        restart: unless-stopped
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@admin.com
            PGADMIN_DEFAULT_PASSWORD: admin
        labels:
            - 'traefik.enable=true'
            - 'traefik.docker.network=web'
            - 'traefik.http.routers.pgadmin.rule=Host(`pgadmin.localhost`)'
            - 'traefik.http.services.pgadmin.loadbalancer.server.port=80'
        networks:
            - web
        depends_on:
            - traefik
            - postgresql

    prometheus:
        image: prom/prometheus:latest
        restart: unless-stopped
        networks:
            - web
        ports:
            - '9090:9090'
        volumes:
            - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
            - prometheus_data:/prometheus
        labels:
            - 'traefik.enable=true'
            - 'traefik.docker.network=web'
            - 'traefik.http.routers.prometheus.rule=Host(`prometheus.localhost`)'
            - 'traefik.http.services.prometheus.loadbalancer.server.port=9090'
        depends_on:
            - traefik
        extra_hosts:
            - "host.docker.internal:host-gateway"
    grafana:
      image: grafana/grafana-enterprise:latest
      restart: unless-stopped
      networks:
        - web
      volumes:
        - grafana_data:/var/lib/grafana
      labels:
        - 'traefik.enable=true'
        - 'traefik.docker.network=web'
        - 'traefik.http.routers.grafana.rule=Host(`grafana.localhost`)'
        - 'traefik.http.services.grafana.loadbalancer.server.port=3000'
      depends_on:
        - traefik
        - prometheus
networks:
    web:
        external: true

volumes:
    prometheus_data:
    grafana_data:
