FROM nvcr.io/nvidia/tritonserver:24.10-py3

# обновляем pip
RUN python3 -m pip install --upgrade pip

# ставим зависимости для Python backend моделей
RUN pip install --no-cache-dir \
    torch==2.3.1 \
    numpy==1.26.4
# запуск docker build -t klin-triton -f Dockerfile.triton .
