version: '3.9'

services:
  klin_api_development:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - web
    environment:
      DATABASE_URL: ${DATABASE_URL}
      RABBIT_URL: ${RABBIT_URL}
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.teamtasker_its_api_development.rule=Host(`localhost`)  && PathPrefix(`/api`)"
      - "traefik.http.services.teamtasker_its_api_development.loadbalancer.server.port=8008"
    command:
      [ "/code/.venv/bin/python", "-m", "granian", "--interface", "asgi", "--host", "0.0.0.0", "--port", "8008", "app.presentation.litestar.run:app" ]

  klin_processor_worker_development:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - web
    environment:
      DATABASE_URL: ${DATABASE_URL}
      RABBIT_URL: ${RABBIT_URL}
    command:
      [ "/code/.venv/bin/python", "-m", "faststream", "run", "app.presentation.faststream.app:app" ]
networks:
  web:
    external: true
