# Default target
default: help

help:
	@echo Avaliable commands:
	@echo .
	@echo General:
	@echo make init-env            # create .env from example.env and backfill new keys
	@echo make migration           # create and auto-apply an Alembic migration for the main database
	@echo make migration-repair    # repair a broken local Alembic state using native Alembic commands
	@echo .
	@echo For development:
	@echo make uv-dev              # create and sync .venv with dev dependencies
	@echo make pre-commit          # install all required pre-commit hooks
	@echo make lint                # Start full project linting (including sandbox) and pylint for app
	@echo make test                # Start application tests with coverage
	@echo make ci-lint             # Run the same lint checks as the GitHub CI lint job
	@echo make ci-test             # Run the same test checks as the GitHub CI test job
	@echo make ci                  # Run both GitHub CI jobs locally
	@echo make start-api-local     # Launch API locally on port 8008
	@echo make start-queue-local   # Launch Queue locally
	@echo make triton-up           # Launch only the local Triton server container
	@echo .
	@echo For production \ docker:
	@echo make infra-up \ -down    # Full docker infra up/down
	@echo make app-up \ -down      # Full docker application up/down
	@echo make docker-stop         # Full docker stop (both infra and app)


init-env:
	python helpers/sync_env.py --template example.env --env .env

migration:
	alembic revision --autogenerate -m "Autogenerated migration"
	alembic upgrade head

migration-repair:
	alembic stamp base --purge
	alembic revision --autogenerate --head base -m "Autogenerated migration"
	alembic upgrade head


uv-dev:
	uv venv --allow-existing
	uv sync --dev

pre-commit:
	uv run pre-commit install
	uv run pre-commit install --hook-type pre-push

lint: uv-dev
	uv run ruff check --fix
	uv run ruff format
	uv run ty check
	uv run -m pylint app

test: uv-dev
	uv run pytest -q --maxfail=1

ci-lint:
	uv venv --allow-existing
	uv sync --group ci --frozen --no-install-project
	uv run --no-sync ruff check app helpers tests
	uv run --no-sync ruff format --check app helpers tests
	uv run --no-sync ty check app helpers tests
	uv run --no-sync -m pylint --jobs=0 app
	uv run --no-sync -m mypy app helpers tests

ci-test:
	uv venv --allow-existing
	uv sync --group ci --frozen --no-install-project
	uv run --no-sync pytest -q --maxfail=1
	uv run --no-sync -m coverage report

ci: ci-lint ci-test ci-mypy

ci-python: ci


start-api-local:
	uv run -m uvicorn --host 0.0.0.0 --port 8008 app.presentation.litestar.run:app

start-queue-local:
	uv run -m faststream run app.presentation.faststream.app:app

triton-up: init-env
	docker compose --env-file .env -f docker/docker-compose.infra.yml up -d triton


infra-up: init-env
	docker compose --env-file .env -f docker/docker-compose.infra.yml up --build -d

infra-down:
	docker compose --env-file .env -f docker/docker-compose.infra.yml down

app-up: init-env
	docker compose --env-file .env -f docker/docker-compose.yml up --build -d

app-down:
	docker compose --env-file .env -f docker/docker-compose.yml down

docker-stop:
	docker compose --env-file .env -f docker/docker-compose.yml stop
	docker compose --env-file .env -f docker/docker-compose.infra.yml stop
