# Default target
default: help


help:
	@echo Avaliable commands:
	@echo .
	@echo General:
	@echo make init-env            # creating .env from example.env (if .env doesn't exist)
	@echo make migration           # create and auto-apply alembic migrations for database
	@echo .
	@echo For development:
	@echo make uv-dev              # create and sync .venv with dev dependencies
	@echo make pre-commit          # install all required pre-commit hooks
	@echo make lint                # Start full project linting (including sandbox) and pylint for app
	@echo make test                # Start application tests
	@echo make start-api-local     # Launch API locally on port 8008
	@echo make start-queue-local   # Launch Queue locally
	@echo .
	@echo For production \ docker:
	@echo make infra-up \ -down    # Full docker infra start/stop
	@echo make app-up \ -down      # Full docker application start/stop
	@echo make docker-stop         # Full docker stop (both infra and app)


init-env:
ifeq ($(OS),Windows_NT)
	@powershell -NoProfile -Command "if (Test-Path '.env') { Write-Host '.env already exists' } else { Copy-Item 'example.env' '.env'; Write-Host 'created .env from example.env' }"
else
	@if [ ! -f .env ]; then \
		cp example.env .env; \
		echo "Создан .env из example.env"; \
	else \
		echo ".env уже существует"; \
	fi
endif

migration:
	alembic revision --autogenerate -m "Autogenerated migration"
	alembic upgrade head

uv-dev:
	uv venv --allow-existing
	uv sync --dev

pre-commit:
	uv run pre-commit install
	uv run pre-commit install --hook-type pre-push

lint: uv-dev
	uv run ruff check --fix
	uv run ruff format
	uv run -m mypy .
	uv run pylint app

test:
	uv run pytest

start-api-local:
	uv run -m uvicorn --host 0.0.0.0 --port 8008 app.presentation.litestar.run:app

start-queue-local:
	uv run -m faststream run app.presentation.faststream.app:app


infra-up: init-env
	docker compose -f docker-compose.infra.yml up --build -d

infra-down:
	docker compose -f docker-compose.infra.yml down

app-up: init-env
	docker compose -f docker-compose.yml up --build -d

app-down:
	docker compose -f docker-compose.yml down

docker-stop:
	docker compose -f docker-compose.yml stop
	docker compose -f docker-compose.infra.yml stop
