"""empty message

Revision ID: 0f97cd486d9e
Revises: 514c4071b5b6
Create Date: 2026-03-10 16:56:03.254734

"""

from collections.abc import Sequence

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "0f97cd486d9e"
down_revision: str | Sequence[str] | None = "514c4071b5b6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "klin", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "klin", type_="unique")
    # ### end Alembic commands ###
