"""Autogenerated migration

Revision ID: 8aee103168a8
Revises: ab238fe8af7d
Create Date: 2026-03-26 21:37:00.196003

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "8aee103168a8"
down_revision: str | Sequence[str] | None = "ab238fe8af7d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_klin_stream_created_at"), table_name="klin_stream")
    op.drop_index(op.f("ix_klin_stream_is_removed"), table_name="klin_stream")
    op.drop_table("klin_stream")
    op.alter_column(
        "klin_mae_result",
        "camera_id",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=False,
    )
    op.alter_column(
        "klin_mae_result",
        "event_id",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=False,
    )
    op.alter_column(
        "klin_mae_result",
        "label",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=False,
    )
    op.alter_column(
        "klin_mae_result",
        "is_removed",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "klin_mae_result",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "klin_mae_result",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(op.f("idx_mae_camera_id"), table_name="klin_mae_result")
    op.drop_index(op.f("idx_mae_stream_id"), table_name="klin_mae_result")
    op.drop_constraint(
        op.f("klin_mae_result_event_id_key"), "klin_mae_result", type_="unique"
    )
    op.create_index(
        op.f("ix_klin_mae_result_camera_id"),
        "klin_mae_result",
        ["camera_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_klin_mae_result_created_at"),
        "klin_mae_result",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_klin_mae_result_event_id"),
        "klin_mae_result",
        ["event_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_klin_mae_result_is_removed"),
        "klin_mae_result",
        ["is_removed"],
        unique=False,
    )
    op.create_index(
        op.f("ix_klin_mae_result_stream_id"),
        "klin_mae_result",
        ["stream_id"],
        unique=False,
    )
    op.create_unique_constraint(None, "klin_mae_result", ["id"])
    op.drop_constraint(op.f("fk_mae_stream"), "klin_mae_result", type_="foreignkey")
    op.create_foreign_key(
        None, "klin_mae_result", "klin_stream_state", ["stream_id"], ["id"]
    )
    op.alter_column(
        "klin_stream_state",
        "camera_id",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=False,
    )
    op.alter_column(
        "klin_stream_state",
        "camera_url",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=True,
    )
    op.alter_column(
        "klin_stream_state",
        "state",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=False,
    )
    op.alter_column(
        "klin_stream_state",
        "last_x3d_label",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=True,
    )
    op.alter_column(
        "klin_stream_state",
        "last_mae_label",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=True,
    )
    op.alter_column(
        "klin_stream_state",
        "objects",
        existing_type=postgresql.ARRAY(sa.TEXT()),
        type_=sa.ARRAY(sa.String()),
        existing_nullable=True,
    )
    op.alter_column(
        "klin_stream_state",
        "all_classes",
        existing_type=postgresql.ARRAY(sa.TEXT()),
        type_=sa.ARRAY(sa.String()),
        existing_nullable=True,
    )
    op.alter_column(
        "klin_stream_state",
        "is_removed",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "klin_stream_state",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "klin_stream_state",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(
        op.f("idx_klin_stream_state_camera_id"), table_name="klin_stream_state"
    )
    op.drop_index(op.f("idx_klin_stream_state_state"), table_name="klin_stream_state")
    op.drop_constraint(
        op.f("klin_stream_state_camera_id_key"), "klin_stream_state", type_="unique"
    )
    op.create_index(
        op.f("ix_klin_stream_state_camera_id"),
        "klin_stream_state",
        ["camera_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_klin_stream_state_created_at"),
        "klin_stream_state",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_klin_stream_state_is_removed"),
        "klin_stream_state",
        ["is_removed"],
        unique=False,
    )
    op.create_index(
        op.f("ix_klin_stream_state_state"), "klin_stream_state", ["state"], unique=False
    )
    op.create_unique_constraint(None, "klin_stream_state", ["id"])
    op.alter_column(
        "klin_x3d_result",
        "camera_id",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=False,
    )
    op.alter_column(
        "klin_x3d_result",
        "event_id",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=False,
    )
    op.alter_column(
        "klin_x3d_result",
        "label",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=False,
    )
    op.alter_column(
        "klin_x3d_result",
        "is_removed",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "klin_x3d_result",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "klin_x3d_result",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(op.f("idx_x3d_camera_id"), table_name="klin_x3d_result")
    op.drop_index(op.f("idx_x3d_stream_id"), table_name="klin_x3d_result")
    op.drop_constraint(
        op.f("klin_x3d_result_event_id_key"), "klin_x3d_result", type_="unique"
    )
    op.create_index(
        op.f("ix_klin_x3d_result_camera_id"),
        "klin_x3d_result",
        ["camera_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_klin_x3d_result_created_at"),
        "klin_x3d_result",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_klin_x3d_result_event_id"),
        "klin_x3d_result",
        ["event_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_klin_x3d_result_is_removed"),
        "klin_x3d_result",
        ["is_removed"],
        unique=False,
    )
    op.create_index(
        op.f("ix_klin_x3d_result_stream_id"),
        "klin_x3d_result",
        ["stream_id"],
        unique=False,
    )
    op.create_unique_constraint(None, "klin_x3d_result", ["id"])
    op.drop_constraint(op.f("fk_x3d_stream"), "klin_x3d_result", type_="foreignkey")
    op.create_foreign_key(
        None, "klin_x3d_result", "klin_stream_state", ["stream_id"], ["id"]
    )
    op.alter_column(
        "klin_yolo_result",
        "camera_id",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=False,
    )
    op.alter_column(
        "klin_yolo_result",
        "event_id",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=False,
    )
    op.alter_column(
        "klin_yolo_result",
        "is_removed",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "klin_yolo_result",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "klin_yolo_result",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(op.f("idx_yolo_camera_id"), table_name="klin_yolo_result")
    op.drop_index(op.f("idx_yolo_stream_id"), table_name="klin_yolo_result")
    op.drop_constraint(
        op.f("klin_yolo_result_event_id_key"), "klin_yolo_result", type_="unique"
    )
    op.create_index(
        op.f("ix_klin_yolo_result_camera_id"),
        "klin_yolo_result",
        ["camera_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_klin_yolo_result_created_at"),
        "klin_yolo_result",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_klin_yolo_result_event_id"),
        "klin_yolo_result",
        ["event_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_klin_yolo_result_is_removed"),
        "klin_yolo_result",
        ["is_removed"],
        unique=False,
    )
    op.create_index(
        op.f("ix_klin_yolo_result_stream_id"),
        "klin_yolo_result",
        ["stream_id"],
        unique=False,
    )
    op.create_unique_constraint(None, "klin_yolo_result", ["id"])
    op.drop_constraint(op.f("fk_yolo_stream"), "klin_yolo_result", type_="foreignkey")
    op.create_foreign_key(
        None, "klin_yolo_result", "klin_stream_state", ["stream_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "klin_yolo_result", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_yolo_stream"),
        "klin_yolo_result",
        "klin_stream_state",
        ["stream_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(None, "klin_yolo_result", type_="unique")
    op.drop_index(op.f("ix_klin_yolo_result_stream_id"), table_name="klin_yolo_result")
    op.drop_index(op.f("ix_klin_yolo_result_is_removed"), table_name="klin_yolo_result")
    op.drop_index(op.f("ix_klin_yolo_result_event_id"), table_name="klin_yolo_result")
    op.drop_index(op.f("ix_klin_yolo_result_created_at"), table_name="klin_yolo_result")
    op.drop_index(op.f("ix_klin_yolo_result_camera_id"), table_name="klin_yolo_result")
    op.create_unique_constraint(
        op.f("klin_yolo_result_event_id_key"),
        "klin_yolo_result",
        ["event_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_index(
        op.f("idx_yolo_stream_id"), "klin_yolo_result", ["stream_id"], unique=False
    )
    op.create_index(
        op.f("idx_yolo_camera_id"), "klin_yolo_result", ["camera_id"], unique=False
    )
    op.alter_column(
        "klin_yolo_result",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "klin_yolo_result",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "klin_yolo_result",
        "is_removed",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "klin_yolo_result",
        "event_id",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.alter_column(
        "klin_yolo_result",
        "camera_id",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.drop_constraint(None, "klin_x3d_result", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_x3d_stream"),
        "klin_x3d_result",
        "klin_stream_state",
        ["stream_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(None, "klin_x3d_result", type_="unique")
    op.drop_index(op.f("ix_klin_x3d_result_stream_id"), table_name="klin_x3d_result")
    op.drop_index(op.f("ix_klin_x3d_result_is_removed"), table_name="klin_x3d_result")
    op.drop_index(op.f("ix_klin_x3d_result_event_id"), table_name="klin_x3d_result")
    op.drop_index(op.f("ix_klin_x3d_result_created_at"), table_name="klin_x3d_result")
    op.drop_index(op.f("ix_klin_x3d_result_camera_id"), table_name="klin_x3d_result")
    op.create_unique_constraint(
        op.f("klin_x3d_result_event_id_key"),
        "klin_x3d_result",
        ["event_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_index(
        op.f("idx_x3d_stream_id"), "klin_x3d_result", ["stream_id"], unique=False
    )
    op.create_index(
        op.f("idx_x3d_camera_id"), "klin_x3d_result", ["camera_id"], unique=False
    )
    op.alter_column(
        "klin_x3d_result",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "klin_x3d_result",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "klin_x3d_result",
        "is_removed",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "klin_x3d_result",
        "label",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.alter_column(
        "klin_x3d_result",
        "event_id",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.alter_column(
        "klin_x3d_result",
        "camera_id",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.drop_constraint(None, "klin_stream_state", type_="unique")
    op.drop_index(op.f("ix_klin_stream_state_state"), table_name="klin_stream_state")
    op.drop_index(
        op.f("ix_klin_stream_state_is_removed"), table_name="klin_stream_state"
    )
    op.drop_index(
        op.f("ix_klin_stream_state_created_at"), table_name="klin_stream_state"
    )
    op.drop_index(
        op.f("ix_klin_stream_state_camera_id"), table_name="klin_stream_state"
    )
    op.create_unique_constraint(
        op.f("klin_stream_state_camera_id_key"),
        "klin_stream_state",
        ["camera_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_index(
        op.f("idx_klin_stream_state_state"),
        "klin_stream_state",
        ["state"],
        unique=False,
    )
    op.create_index(
        op.f("idx_klin_stream_state_camera_id"),
        "klin_stream_state",
        ["camera_id"],
        unique=False,
    )
    op.alter_column(
        "klin_stream_state",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "klin_stream_state",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "klin_stream_state",
        "is_removed",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "klin_stream_state",
        "all_classes",
        existing_type=sa.ARRAY(sa.String()),
        type_=postgresql.ARRAY(sa.TEXT()),
        existing_nullable=True,
    )
    op.alter_column(
        "klin_stream_state",
        "objects",
        existing_type=sa.ARRAY(sa.String()),
        type_=postgresql.ARRAY(sa.TEXT()),
        existing_nullable=True,
    )
    op.alter_column(
        "klin_stream_state",
        "last_mae_label",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.alter_column(
        "klin_stream_state",
        "last_x3d_label",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.alter_column(
        "klin_stream_state",
        "state",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.alter_column(
        "klin_stream_state",
        "camera_url",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.alter_column(
        "klin_stream_state",
        "camera_id",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.drop_constraint(None, "klin_mae_result", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_mae_stream"),
        "klin_mae_result",
        "klin_stream_state",
        ["stream_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(None, "klin_mae_result", type_="unique")
    op.drop_index(op.f("ix_klin_mae_result_stream_id"), table_name="klin_mae_result")
    op.drop_index(op.f("ix_klin_mae_result_is_removed"), table_name="klin_mae_result")
    op.drop_index(op.f("ix_klin_mae_result_event_id"), table_name="klin_mae_result")
    op.drop_index(op.f("ix_klin_mae_result_created_at"), table_name="klin_mae_result")
    op.drop_index(op.f("ix_klin_mae_result_camera_id"), table_name="klin_mae_result")
    op.create_unique_constraint(
        op.f("klin_mae_result_event_id_key"),
        "klin_mae_result",
        ["event_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_index(
        op.f("idx_mae_stream_id"), "klin_mae_result", ["stream_id"], unique=False
    )
    op.create_index(
        op.f("idx_mae_camera_id"), "klin_mae_result", ["camera_id"], unique=False
    )
    op.alter_column(
        "klin_mae_result",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "klin_mae_result",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "klin_mae_result",
        "is_removed",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "klin_mae_result",
        "label",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.alter_column(
        "klin_mae_result",
        "event_id",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.alter_column(
        "klin_mae_result",
        "camera_id",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.create_table(
        "klin_stream",
        sa.Column("camera_id", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("camera_url", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("state", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("x3d", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("mae", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("yolo", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "all_classes",
            postgresql.ARRAY(sa.VARCHAR()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "objects",
            postgresql.ARRAY(sa.VARCHAR()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("is_removed", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("klin_stream_pkey")),
    )
    op.create_index(
        op.f("ix_klin_stream_is_removed"), "klin_stream", ["is_removed"], unique=False
    )
    op.create_index(
        op.f("ix_klin_stream_created_at"), "klin_stream", ["created_at"], unique=False
    )
    # ### end Alembic commands ###
