"""Autogenerated migration

Revision ID: 9363382a1e84
Revises:
Create Date: 2026-03-25 19:29:15.719520

"""

from collections.abc import Sequence


# revision identifiers, used by Alembic.
revision: str = "9363382a1e84"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
