"""Autogenerated migration

Revision ID: 9e0aaedc9dc1
Revises: 
Create Date: 2026-03-10 16:30:50.259826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e0aaedc9dc1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('klin',
    sa.Column('response_url', sa.String(), nullable=True),
    sa.Column('video_path', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('x3d', sa.String(), nullable=True),
    sa.Column('mae', sa.String(), nullable=True),
    sa.Column('yolo', sa.String(), nullable=True),
    sa.Column('all_classes', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('objects', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('is_removed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_klin_created_at'), 'klin', ['created_at'], unique=False)
    op.create_index(op.f('ix_klin_is_removed'), 'klin', ['is_removed'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_klin_is_removed'), table_name='klin')
    op.drop_index(op.f('ix_klin_created_at'), table_name='klin')
    op.drop_table('klin')
    # ### end Alembic commands ###
