"""Autogenerated migration

Revision ID: e1883ee841c6
Revises: 0f97cd486d9e
Create Date: 2026-03-19 15:21:56.992965

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "e1883ee841c6"
down_revision: str | Sequence[str] | None = "0f97cd486d9e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "klin_stream",
        sa.Column("camera_id", sa.String(), nullable=True),
        sa.Column("camera_url", sa.String(), nullable=True),
        sa.Column("state", sa.String(), nullable=False),
        sa.Column("x3d", sa.String(), nullable=True),
        sa.Column("mae", sa.String(), nullable=True),
        sa.Column("yolo", sa.String(), nullable=True),
        sa.Column("all_classes", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("objects", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("is_removed", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_index(
        op.f("ix_klin_stream_created_at"), "klin_stream", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_klin_stream_is_removed"), "klin_stream", ["is_removed"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_klin_stream_is_removed"), table_name="klin_stream")
    op.drop_index(op.f("ix_klin_stream_created_at"), table_name="klin_stream")
    op.drop_table("klin_stream")
    # ### end Alembic commands ###
