FROM apache/airflow:3.1.7

WORKDIR /opt/airflow

COPY pyproject.toml uv.lock ./

RUN pip install --no-cache-dir uv==0.11.19 && \
    uv pip install --requirements pyproject.toml && \
    uv pip install --no-cache-dir \
    grpcio==1.67.1 \
    grpcio-tools==1.67.1 \
    apache-airflow-providers-docker==4.5.4 \
    apache-airflow-providers-fab==3.3.0
