FROM apache/airflow:3.1.7

RUN pip install uv

COPY pyproject.toml uv.lock ./

RUN uv pip install --requirements pyproject.toml

RUN uv pip install --no-cache-dir \
    grpcio==1.67.1 \
    grpcio-tools==1.67.1

RUN uv pip install --no-cache-dir \
    apache-airflow-providers-docker \
    apache-airflow-providers-fab==3.3.0
