name: "x3d_violence"
backend: "python"

max_batch_size: 8

input [
  {
    name: "video"
    data_type: TYPE_FP32
    dims: [3,16,224,224]
  }
]

output [
  {
    name: "logits"
    data_type: TYPE_FP32
    dims: [2]
  }
]
