from pathlib import Path

from alembic import command
from alembic.config import Config

from app.config import app_settings
from app.models import Model


PROJECT_ROOT = Path(__file__).resolve().parents[2]
MIGRATIONS_DIR = PROJECT_ROOT / "app/infrastructure/database/migrations"


def _autogenerated_revision_text(tmp_path: Path, monkeypatch) -> str:
    versions_dir = tmp_path / "versions"
    database_path = tmp_path / "schema.db"

    versions_dir.mkdir()

    # Alembic's env.py reads DATABASE_URL through app_settings, which caches values.
    app_settings.env_properties.pop("DATABASE_URL", None)
    monkeypatch.setenv("DATABASE_URL", f"sqlite:///{database_path.as_posix()}")

    try:
        config = Config()
        config.set_main_option("script_location", str(MIGRATIONS_DIR))
        config.set_main_option("prepend_sys_path", ".")
        config.set_main_option("path_separator", "os")
        config.set_main_option("sqlalchemy.url", "%(DATABASE_URL)s?async_fallback=True")
        config.set_main_option("version_locations", str(versions_dir))

        command.revision(config, message="autogen_check", autogenerate=True)

        revision_paths = sorted(versions_dir.glob("*.py"))
        assert len(revision_paths) == 1
        return revision_paths[0].read_text(encoding="utf-8")
    finally:
        app_settings.env_properties.pop("DATABASE_URL", None)


def test_alembic_autogenerate_sees_all_model_tables(
    tmp_path: Path, monkeypatch
) -> None:
    revision_text = _autogenerated_revision_text(tmp_path, monkeypatch)

    for table_name in Model.metadata.tables:
        assert f'"{table_name}"' in revision_text or f"'{table_name}'" in revision_text


def test_alembic_autogenerate_includes_stream_snapshot_columns(
    tmp_path: Path, monkeypatch
) -> None:
    revision_text = _autogenerated_revision_text(tmp_path, monkeypatch)

    for column_name in (
        "last_x3d_label",
        "last_x3d_confidence",
        "last_mae_label",
        "last_mae_confidence",
    ):
        assert (
            f'"{column_name}"' in revision_text or f"'{column_name}'" in revision_text
        )
